version: '3'

services:
  node:
      build:
        context: ./server
        dockerfile: Dockerfile
      container_name: node-latest
      ports:
        - "3000:3000"
      links:
        - "db"
      networks:
        - applectura_my-network
  db:
      build:
        context: ./database
        dockerfile: Dockerfile
      container_name: mysql-latest
      ports:
        - "165.22.62.165:3307:3306"
      volumes:
        - /var/lib/mysql-data:/var/lib/mysql
      networks:
        - applectura_my-network
  web:
      build:
        context: ./client
        dockerfile: Dockerfile
      container_name: nginx-alpine
      ports:
        - "165.22.62.165:8080:80"
      networks:
        - applectura_my-network
      links:
        - "node"
networks:
  applectura_my-network:
