version: '3.1'

services:
  node:
      build:
        context: ./server
        dockerfile: Dockerfile
      container_name: node-latest
      ports:
        - "3000:3000"
      networks:
        - my-network
      links:
        - "db"
  db:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      container_name: mysql-latest
      ports:
          - "165.22.62.165:3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: mypass
      volumes:
          - /var/lib/mysql-data:/var/lib/mysql
      networks:
          - my-network
  web:
      build:
        context: ./client
        dockerfile: Dockerfile
      container_name: nginx-alpine
      ports:
        - "165.22.62.165:8080:80"
      networks:
        - my-network
      links:
        - "node"
networks:
  my-network:
